### ISSUE TITLE
Module should handle versions of PostgreSQL 9.3 and above

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/nd_genotypes#10]
Currently this module only handles PostgreSQL 9.3 and 9.4, when there's no reason it shouldn't allow greater than 9.4 as well. I think you only need to change a single line to be a greater than or equal to: https://github.com/UofS-Pulse-Binfo/nd_genotypes/blob/7.x-3.x/includes/nd_genotypes.mview.inc#L90

May I suggest also informing the user during installation/enabling of the module if their PostgreSQL version is out of date? :-) See an example in the genotypes_loader module here:  genotypes_loader/genotypes_loader.install

**Comment by laceysanderson** [comment]
Fixed by PR
