### ISSUE TITLE
Error trying to sync Mview

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/nd_genotypes#11]
I'm receiving a rather unhelpful error message on the terminal (from running a Tripal Job) when I try to sync mviews:

`Partition: Lens...
   Sync'ing genotypes to the mview_ndg_calls mview...
    - Creating mview_ndg_lens_calls if it doesn't already exist...
Cannot modify header information - headers already sent by (output started at /usr/share/php/drush/includes/output.inc:37) common.inc:706                                                      [warning] 
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                           [error]
`

I can confirm that our site has the mview_ndg_lens_calls table already. Commenting out all of the functions creating tables seems to have allowed us to circumvent the problem.

**Comment by carolyncaron** [comment]
After testing PR #12, I no longer get any errors on the terminal, but I still cannot see any genotype calls in the genotype matrix. :( Lacey has confirmed that all of the mview tables are empty after syncing.

**Comment by laceysanderson** [comment]
Fixed via PR
