### ISSUE TITLE
Genotype matrix won't allow to search for 1 result (variant)

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/nd_genotypes#17]
Currently, genotype matrix gives an error page if there's only one result

For example, we know we have "LcChr1p**5326**" and "LcChr1p**5361**" for "CDC Imax AGL":

Search from position 5325 to position 5361 is fine:
![screenshot-2](https://user-images.githubusercontent.com/26550071/44364600-aa06a280-a484-11e8-95e2-32f5af8426db.png)

But, search from position 5327 to position 5361 will give an Error page:
![screenshot](https://user-images.githubusercontent.com/26550071/44363971-02d53b80-a483-11e8-89b7-9fbb046619ec.png)

Also, search from position 5361 to position 5361 won't generate any result:
![screenshot-1](https://user-images.githubusercontent.com/26550071/44364376-0d440500-a484-11e8-86f4-7db0275581d0.png)

**Comment by laceysanderson** [comment]
Fixed by PR
