### ISSUE TITLE
SO bundle terms dont match Tripal defaults

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/nd_genotypes#34]
bundles look for SO terms before attaching.  For example, before attaching to Sequence Variant, it looks for `sequence_variant`

```php


  // FEATURE-BASED CONTENT TYPES.
  /////////////////////////////////////
  if (isset($bundle->data_table) AND ($bundle->data_table == 'feature')) {

    dpm($bundle);
    dpm($term);

    // Variant Genotype Summary Field.
    //---------------------------------
    // Only add the Variant Genotype Summary field
    // if the current Tripal Content Type is SO:sequence_variant.
    if ($term->name == 'sequence_variant') {

```

Unfortunately, Tripal installs the terms as Sequence Variant.  This means the fields never attach.  You can see this by my dump of the TripalTerm object (from a freshly installed tripal site):

<img width="1029" alt="Screen Shot 2019-05-11 at 10 41 24 PM" src="https://user-images.githubusercontent.com/7063154/57577110-f42e1a80-743d-11e9-957b-e82707a6100b.png">

heres the chado install of hte entity type (and the wrong term name)

```php
  //
  // Create the 'Sequence Variant' entity type.
  //
  $args = [
    'vocabulary' => 'SO',
    'accession' => '0001060',
    'term_name' => 'Sequence Variant',
    'storage_args' => [
      'data_table' => 'feature',
      'type_column' => 'type_id',
    ],
    'category' => 'Genetic',
  ];
```
Which is correct, Sequence Variant or sequence_variant?  Looks to me like sequence_variant.  If so, we should correct in core? 
Finally a slapdash fix can look something like this:

```php
    if ($term->name == 'sequence_variant' || $term->name == 'Sequence Variant') {
```

or, maybe you should check by accession instead?

**Comment by laceysanderson** [comment]
Interesting... I should likely check by accession. That said, we should likely get this fixed in Tripal Core as well since I believe the term name should match the cvterm.name (`sequence_variant`)

**Comment by bradfordcondon** [comment]
Submitted a PR to core to resolve, if merged this module will require no changes.

**Comment by bradfordcondon** [comment]
merged in core.
