### ISSUE TITLE
genotype link fields do not autoattach

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/nd_genotypes#39]
it would be great if genotype matrix link fields (#21) autoattached to relevant content types.  Right now they have to be manually attached via hte GUI.  If its not possible, there should be a hard-to-miss notice about this on the install docs page.

**Comment by laceysanderson** [comment]
These fields now automatically attach to sequence variants and genetic markers. Thanks for the suggestion!
