### ISSUE TITLE
PHP Fatal error:  Cannot redeclare nd_genotypes_genotype_call_schema_template()

### ISSUE THREAD

**Issue by Xaiku** [UofS-Pulse-Binfo/nd_genotypes#54]
Hi everybody,

I uninstalled and reinstalled nd_genotypes and this is the error I got after trying to pm-enable nd_genotypes:
![image](https://user-images.githubusercontent.com/73877812/105611196-1acbea80-5db4-11eb-894f-a6fdbf444664.png)

I looked into the files and here are some screenshots:
genotypes_loader.install
![image](https://user-images.githubusercontent.com/73877812/105611221-3fc05d80-5db4-11eb-824b-68a1be3adb58.png)
nd_genotypes.mview.inc
![image](https://user-images.githubusercontent.com/73877812/105611238-55358780-5db4-11eb-9ea7-ac1b85484340.png)

The two files contain the same function. Do I have to manually delete 1 function from 1 file or is there another way?

**Comment by laceysanderson** [comment]
Oh no 😶  This was missed when we upgraded the genotypes loader to be independent from nd_genotypes and is a copy/paste error. I have a PR to fix it on [Genotypes Loader](https://github.com/UofS-Pulse-Binfo/genotypes_loader/pull/51) which will be merged as soon as tests pass and will resolve this.

**Comment by laceysanderson** [comment]
There. It has been merged into master for Genotypes Loader. Please update your version of [that module](https://github.com/uofs-pulse-binfo/genotypes_loader/) and then try again. So Sorry for the difficulties!!!

**Comment by Xaiku** [comment]
Hey @laceysanderson,

I updated my genotypes_loader version, but when I try to pm-enable genotypes_loader it gives me the following error:
![image](https://user-images.githubusercontent.com/73877812/105674972-9b8c0300-5ee8-11eb-90c3-f7fdd8787c05.png)

**Comment by laceysanderson** [comment]
I'm so sorry -this is what I get for fixing bugs on the weekend :-( 

I have removed the duplicate function in [7336dcc](https://github.com/UofS-Pulse-Binfo/genotypes_loader/commit/7336dcca2e69de1d9b168ad80aa8122bba3321d7) and tested importing genotypes manually according to https://genotypes-loader.readthedocs.io/en/latest/demo.html with nd_genotypes already installed.

**Comment by Xaiku** [comment]
I updated the genotypes_loader folder and I got no errors with enabling genotypes_loader and nd_genotypes with pm-enable.
Thank you for your help!
