### ISSUE TITLE
Error: function create_point(integer, bigint) does not exist

### ISSUE THREAD

**Issue by Xaiku** [UofS-Pulse-Binfo/nd_genotypes#55]
Hey everybody,

I followed the following steps to test nd_genotypes:
![image](https://user-images.githubusercontent.com/73877812/106038630-79f16e00-60d8-11eb-8f7e-44ed876fb390.png)

but when I ran the sync job with the drush command, it gave me the following error:
![image](https://user-images.githubusercontent.com/73877812/106038577-6b0abb80-60d8-11eb-9e8f-c56828ad5e47.png)
It still gives me 100% completed on my jobs lists. 
![image](https://user-images.githubusercontent.com/73877812/106038970-da80ab00-60d8-11eb-895a-5726d3c80fa7.png)

**Comment by laceysanderson** [comment]
Hi @Xaiku 

This is actually a well known Chado bug which will be fixed in Chado 1.4: https://github.com/GMOD/Chado/issues/65

In the meantime, this [GIST explains how to fix it in a Tripal site](https://gist.github.com/laceysanderson/fcd68acc1945c66341ac112be2c12329).

**Comment by Xaiku** [comment]
Hi @laceysanderson,

Everything seems to work now. Thanks a lot!
